pipeline:

  deploy:
    image: docker
    commands:
      - docker deploy --compose-file docker-compose.yml domoticz_zwave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY, AWS_IOT_ENDPOINT_HOST, AWS_REGION ]
